// Connect to API/AngularApi/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { Name } from './models/name';
import { User } from './models/user';
import { RandomUserService } from './random-user.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  public user: User;

  constructor(private userService: RandomUserService) {
    this.user = new User();
    this.user.name = new Name();
  }

  ngOnInit(): void {
    this.userService.getUsers().subscribe(response => {
      this.user = response.results[0];
    })
  }

}

<div>
  <h1>API Test</h1>
  <div *ngIf="user">
    {{user.name.first}} {{user.name.last}}
  </div>
 
</div>

// Connect to API/react-axios-example/src/App.tsx
import { useEffect, useState } from 'react';
import { User } from './models/user';
import { getUsers } from './random-user-api';

function App() {
  const [users, setUsers] = useState<User[]>([]);

  useEffect(() => {
    const populateUsers = async () => {
      try {
        var userResponse = await getUsers();
        setUsers(userResponse.results);
      } catch (e) {
        console.log(e);
      }
    }
    populateUsers();
  }, [])

  return (
    <>
      <h1>API Test</h1>
      {users.length > 0 ? 
        users.map((user, idx) => 
          <div key={idx}>{user.name.first} {user.name.last}</div>
        )
        : 'Loading...'}
    </>
  );
}

export default App;
